### ISSUE TITLE
Results are far from paper claim

### ISSUE THREAD

**Issue by mu-cai** [zhangqianhui/Swapping-Autoencoder-tf#1]
Seems that there are also problems with the result of this tf-version code. And actually, far from the paper claim. Don't know whether it is because that the iterations are not enough or that the re-implementation still has problems.

**Comment by zhangqianhui** [comment]
I think it has three reasons
(1) the iterations are not enough. The original paper uses 8 telsa v100 16GB for training. Haha.....
(2) We use AdaIN, not modulation/demodulation. I will update it in next few days.
(3) The results of paper are selected samples.

**Comment by mu-cai** [comment]
I think AddIN may not be the main problem.
(1), and (3), especially (3) is important



Jichao Zhang <notifications@github.com> 于2020年10月15日周四 下午3:49写道：

**Comment by zhangqianhui** [comment]
yeah, I agree.

**Comment by zhangqianhui** [comment]
Additionally, I will explore Exponential Moving Average for test model. Maybe, it can improve the results.

**Comment by puppet101** [comment]
By the way, why not use the FFHQ dataset? It is about one time larger than CelebaHQ.
